import esbuild from "esbuild";
import esbuildSvelte from "esbuild-svelte";
import process from "node:process";
import { builtinModules as builtins } from "node:module";
import { copyFileSync, existsSync } from "node:fs";
import { join } from "node:path";

/** Copy build outputs into the local test vault when it exists. */
const copyToTestVault = {
	name: "copy-to-test-vault",
	setup(build) {
		build.onEnd((result) => {
			if (result.errors.length > 0) return;
			const dest = join("test-vault", ".obsidian", "plugins", "novelr");
			if (!existsSync(dest)) return;
			for (const f of ["main.js", "manifest.json", "styles.css"]) {
				if (existsSync(f)) copyFileSync(f, join(dest, f));
			}
		});
	},
};

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the GitHub repository of this plugin.
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
	banner: { js: banner },
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2021",
	platform: "browser",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	minify: prod,
	outfile: "main.js",
	conditions: ["svelte", "browser"],
	mainFields: ["svelte", "browser", "module", "main"],
	plugins: [
		esbuildSvelte({
			compilerOptions: { css: "external", dev: !prod },
			filterWarnings: (warning) => !warning.code.startsWith("a11y"),
		}),
		copyToTestVault,
	],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
